"use client";

import { useState, useRef, useCallback } from "react";
import { useRouter } from "next/navigation";
import { FileText, CheckCircle, AlertCircle } from "lucide-react";

// PLACEHOLDER — Erano Consulting to supply final legal text before launch
const TC_PARAGRAPHS = [
  "ERANO CONSULTING — SERVICE AGREEMENT (PLACEHOLDER — final text to be supplied by client before launch)",
  "1. PARTIES: This Service Agreement is entered into between Erano Consulting Limited (the Firm), a consulting firm registered in Ghana, and the client identified in the onboarding application (the Client).",
  "2. SCOPE OF SERVICES: The Firm agrees to provide professional services described in the Client's selected service package. Specific deliverables, timelines, and scope are as agreed during onboarding. Any changes to scope must be documented and agreed in writing by both parties.",
  "3. FEES AND PAYMENT: The Client agrees to pay all fees stated in the invoice generated by the Firm. Payment is due within 5 business days of accepting this Agreement. The Firm reserves the right to suspend services if payment is not received within the agreed period. All fees are quoted in Ghana Cedis (GH₵).",
  "4. PAYMENT METHOD: All payments must be made via direct bank transfer to the Firm's designated account. Proof of payment must be uploaded through the client portal. Services will commence upon successful verification of payment by the Firm.",
  "5. CONFIDENTIALITY: Both parties agree to treat as confidential all non-public information exchanged during this engagement. The Firm will not disclose the Client's financial or business information to third parties without written consent, except where required by Ghanaian law or regulatory authority.",
  "6. CLIENT OBLIGATIONS: The Client agrees to provide accurate, complete, and timely information as required by the Firm. Delays caused by incomplete or inaccurate information provided by the Client may affect delivery timelines and do not relieve the Client of payment obligations.",
  "7. INTELLECTUAL PROPERTY: All reports, analyses, and deliverables produced by the Firm under this Agreement remain the property of the Firm until full payment is received, at which point ownership of the deliverables transfers to the Client.",
  "8. LIMITATIONS OF LIABILITY: The Firm's total liability for any claim arising under this Agreement shall not exceed the total fees paid by the Client for the relevant service. The Firm shall not be liable for indirect, special, or consequential losses.",
  "9. TERMINATION: Either party may terminate this Agreement by giving 14 days written notice. The Client remains liable for fees for services rendered up to the date of termination. The Firm may terminate immediately in the event of material breach by the Client.",
  "10. GOVERNING LAW: This Agreement is governed by the laws of the Republic of Ghana. Any disputes arising shall be subject to the exclusive jurisdiction of the courts of Ghana.",
  "11. ENTIRE AGREEMENT: This Agreement, together with the selected service package and onboarding application, constitutes the entire agreement between the parties and supersedes all prior discussions and representations.",
  "12. ACCEPTANCE: By clicking 'I Accept' below, the Client confirms they have read, understood, and agree to be bound by all terms and conditions stated in this Agreement.",
];

export default function AgreementGate() {
  const router = useRouter();
  const scrollRef = useRef<HTMLDivElement>(null);
  const [scrolledToBottom, setScrolledToBottom] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [accepted, setAccepted] = useState(false);

  const handleScroll = useCallback(() => {
    const el = scrollRef.current;
    if (!el) return;
    if (el.scrollHeight - el.scrollTop - el.clientHeight < 10) setScrolledToBottom(true);
  }, []);

  async function handleAccept() {
    if (!scrolledToBottom || loading) return;
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/portal/agreements/accept", { method: "POST" });
      if (res.status === 409) { router.refresh(); return; }
      if (!res.ok) {
        const body = await res.json() as { error?: string };
        setError(body.error ?? "Something went wrong. Please try again.");
        setLoading(false);
        return;
      }
      setAccepted(true);
      router.refresh();
    } catch {
      setError("Something went wrong. Please try again.");
      setLoading(false);
    }
  }

  if (accepted) {
    return (
      <div className="mb-8 rounded-lg border border-green-200 bg-green-50 p-6 text-center">
        <CheckCircle className="mx-auto mb-2 h-8 w-8 text-green-600" aria-hidden="true" />
        <p className="font-semibold text-green-800">Agreement accepted. Updating your account...</p>
      </div>
    );
  }

  return (
    <section className="mb-8 rounded-lg border border-line bg-off p-6" aria-labelledby="agreement-heading">
      <div className="mb-4 flex items-center gap-3">
        <FileText className="h-5 w-5 text-gold" aria-hidden="true" />
        <h2 id="agreement-heading" className="text-lg font-semibold text-navy">Service Agreement</h2>
      </div>
      <p className="mb-4 text-sm text-body">
        Please read the full agreement below. The accept button is enabled only once you have scrolled to the bottom.
      </p>
      <div
        ref={scrollRef}
        onScroll={handleScroll}
        onMouseEnter={(e) => e.currentTarget.focus()}
        className="mb-4 h-96 overflow-y-scroll rounded border border-line bg-white p-4"
        tabIndex={0}
        role="document"
        aria-label="Service agreement terms and conditions"
      >
        {TC_PARAGRAPHS.map((para) => (
          <p key={para.slice(0, 32)} className="mb-4 text-sm leading-relaxed text-body">{para}</p>
        ))}
      </div>
      {!scrolledToBottom && (
        <p className="mb-3 text-xs text-body" aria-live="polite">
          Scroll to the bottom to enable the accept button.
        </p>
      )}
      {error && (
        <div
          className="mb-3 flex items-center gap-2 rounded border border-red-200 bg-red-50 p-3"
          role="alert"
          aria-live="assertive"
        >
          <AlertCircle className="h-4 w-4 shrink-0 text-red-500" aria-hidden="true" />
          <p className="text-sm text-red-700">{error}</p>
        </div>
      )}
      <button
        type="button"
        onClick={handleAccept}
        disabled={!scrolledToBottom || loading}
        aria-disabled={!scrolledToBottom || loading}
        className="rounded bg-navy px-6 py-2.5 text-sm font-semibold text-gold transition-opacity disabled:cursor-not-allowed disabled:opacity-40"
      >
        {loading ? "Accepting..." : "I Accept the Agreement"}
      </button>
    </section>
  );
}
